"""empty message

Revision ID: 523573891400
Revises: 3e67c415dfcd
Create Date: 2020-11-21 15:04:28.000950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523573891400'
down_revision = '3e67c415dfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
